from turtle import *
from time import sleep
setup(750,750)
shape('turtle')
def drawCircle(size,isfilled):
    if isfilled:
        begin_fill()
    setheading(180)
    circle(size)
    if isfilled:
        end_fill()
def drawRec(length,wide,isfilled):
    if isfilled:
        begin_fill()
    for i in range(2):
        forward(length)
        right(90)
        forward(wide)
        right(90)
    if isfilled:
        end_fill()
def drawHead():
    color('black','cyan')
    penup()
    goto(0,100)
    pendown()
    drawCircle(75,True)
    color('black','white')
    penup()
    goto(0,72)
    pendown()
    drawCircle(60,True)
def drawEyes():
    color('black','white')
    penup()
    goto(-15,80)
    pendown()
    drawCircle(17,True)
    penup()
    goto(19,80)
    pendown()
    drawCircle(17,True)
    color('black')
    penup()
    goto(-8,70)
    pendown()
    drawCircle(6,True)
    penup()
    goto(12,70)
    pendown()
    drawCircle(6,True)
    color('white')
    penup()
    goto(-8,66)
    pendown()
    drawCircle(2,True)
    penup()
    goto(12,66)
    pendown()
    drawCircle(2,True)
def drawBell():
    color('black','yellow')
    penup()
    goto(0,-50)
    pendown()
    drawCircle(8,True)
    color('black')
    penup()
    goto(5,-56)
    pendown()
    drawRec(10,4,False)
    penup()
    goto(0,-62)
    pendown()
    drawCircle(2,True)
def drawMouth():
    color('black')
    penup()
    goto(-30,-20)
    pendown()
    setheading(-27)
    circle(70,55)
    penup()
    goto(0,26)
    pendown()
    goto(0,-25)
def drawNose():
    color('black','red')
    penup()
    goto(0,40)
    pendown()
    drawCircle(7,True)
    penup()
    goto(0,35)
    pendown()
    color('white')
    drawCircle(2,True)
def drawHands():
    color('black','white')
    penup()
    goto(-90,-71)
    pendown()
    drawCircle(15,True)
    penup()
    goto(90,-71)
    pendown()
    drawCircle(15,True)
def drawArms():
    color('black','cyan')
    begin_fill()
    penup()
    goto(-51,-50)
    pendown()
    goto(-51,-75)
    goto(-76,-85)
    goto(-86,-70)
    goto(-51,-50)
    end_fill()
    penup()
    goto(49,-50)
    pendown()
    begin_fill()
    goto(49,-75)
    goto(74,-85)
    goto(84,-70)
    goto(49,-50)
    end_fill()
def drawFeet():
    color('black','white')
    penup()
    goto(-30,-110)
    pendown()
    drawCircle(20,True)
    penup()
    goto(30,-110)
    pendown()
    drawCircle(20,True)
def drawBody():
    color('black','cyan')
    penup()
    goto(0,-35)
    pendown()
    drawCircle(50,True)
    color('black','white')
    penup()
    goto(0,-35)
    pendown()
    drawCircle(40,True)
def drawCollar():
    color('black','red')
    penup()
    goto(35,-45)
    pendown()
    drawRec(70,10,True)
drawHead()
drawEyes()
drawNose()
drawMouth()
drawBody()
drawCollar()
drawBell()
drawArms()
drawHands()
drawFeet()
hideturtle()
sleep(2.5)