

Adjective1=input('ADJECTIVE1= ')
Adjective2=input('ADJECTIVE2= ')
Adjective3=input('ADJECTIVE3= ')
Adjective4=input('ADJECTIVE4= ')
Adjective5=input('ADJECTIVE5= ')
Adjective6=input('ADJECTIVE6= ')
Adjective7=input('ADJECTIVE7= ')
Adjective8=input('ADJECTIVE8= ')
Noun1=input('NOUN1= ')
Noun2=input('NOUN2= ')
ArticleofClothing1=input('CLOTHE1= ')
ArticleofClothing2=input('CLOTHE2= ')
RoominHouse1=input('Room1= ')
FoodItem1=input('food1= ')
FoodItem2=input('food2= ')
Beverage1=input('DRINK1= ')
Beverage2=input('DRINK2= ')
TypeofMusic1=input('MUSIC= ')
Verb1=input('VERB1= ')
Verb2=input('VERB2= ')
Verb3=input('VERB3= ')
Activity1=input('ACTIVITY1= ')
Activity2=input('ACTIVITY2= ')
Activity3=input('ACTIVITY3= ')
story="A Day in the Life of a " +Adjective1 +' '+ Noun1+" One "+Adjective2+" morning, I woke up feeling "+Adjective3+". I got out of bed and put on my favorite "+ArticleofClothing1+". Then, I went to the "+RoominHouse1+" to make breakfast."+"For breakfast, I made myself some "+FoodItem1+" and a cup of "+Beverage1+". While I was eating, I listened to some "+TypeofMusic1+" to help me wake up."+"After breakfast, I "+Verb1+" my teeth and "+Verb2+" my face before heading out to start my day. I had a "+Adjective4+" day planned, filled with "+Activity1+" and "+Activity2+"."+"In the afternoon, I took a break to have some "+FoodItem2+" and a glass of "+Beverage2+". I felt "+Adjective5+" and relaxed."+"In the evening, I "+Verb3+" some "+Activity3+" before getting ready for bed. I brushed my teeth, put on my "+ArticleofClothing2+", and crawled into bed feeling "+Adjective6+"."+"Overall, it was a "+Adjective7+" day in the life of a "+Adjective8+Noun2
print(story)