import matplotlib.pyplot as mp
import pandas as ps
# data=ps.read_csv('csvgames.csv',delimiter=';')
# print(data.head())
# print(data['Rating'].value_counts())
# mp.bar(data['Rating'].value_counts().keys(),data['Rating'].value_counts())
# mp.show()
data=ps.read_csv('internet.csv')
print(data.head())
print(data.shape)
Indonesia=(data[data['Entity']=='Indonesia'])
print(Indonesia)
mp.bar(Indonesia['Year'],Indonesia['Number of Internet users'])
mp.show()
Japan=(data[data['Entity']=='Japan'])
mp.bar(Japan['Year'],Japan['Number of Internet users'])
mp.show()
UnitedStates=(data[data['Entity']=='United States'])
mp.bar(UnitedStates['Year'],UnitedStates['Number of Internet users'])
mp.show()